/**
 * `src/version.ts`, from this package's own `package.json`.
 *
 * The version is an input to the social-card cache key — the composition changes between releases,
 * so a card drawn by an older pagina has to be redrawn — and both rasterisers have to read the same
 * one or each would spend its life redrawing what the other had just drawn. Node could read the
 * manifest at runtime; a browser bundle cannot, so it is generated into the source instead.
 *
 * Committed rather than gitignored: the `development` export condition points at `src/`, so vitest
 * and `pagina dev` import this file without anything having built it first.
 */
import { readFile, writeFile } from "node:fs/promises";

const pkg = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
const out = new URL("../src/version.ts", import.meta.url);
const body = `/**
 * This package's version. Generated by \`scripts/write-version.mjs\`; do not edit.
 *
 * See that script for why it is a literal rather than a read of \`package.json\`.
 */
export const PAGINA_VERSION = ${JSON.stringify(pkg.version)};
`;
const current = await readFile(out, "utf8").catch(() => "");
if (current !== body) await writeFile(out, body);
