/**
 * This package's version. Generated by `scripts/write-version.mjs`; do not edit.
 *
 * See that script for why it is a literal rather than a read of `package.json`.
 */
export const PAGINA_VERSION = "0.4.0";
