/**
 * Drawing social cards in the browser, at publish time.
 *
 * A card is generated by the *build*, in Node, by `@resvg/resvg-js`. Publishing, though, happens
 * here: the editor renders every page and figure client-side and POSTs the result. So a site
 * published from a browser used to keep whatever cards its last build produced — a new post shared
 * as a stale picture, or as no picture at all.
 *
 * This is the second rasteriser. It is emphatically *not* a second card renderer: the composition,
 * the palette ladder, the precedence rules and the content hash all come from `@pagina/core`'s
 * `planCards` and `cardScene`, which is the same code the build calls. What is written here is only
 * the part that is different about a browser — how you turn a Kineglyph scene into PNG bytes
 * without resvg — and the answer is the platform's own: render the scene to SVG, load it into an
 * `<img>`, draw that onto a `<canvas>`, and `toBlob("image/png")`.
 *
 * ## Fonts, which is the whole problem
 *
 * An SVG loaded as an `<img>` is a *document*, not a fragment. It cannot see the page's stylesheets
 * and it is not allowed to fetch anything — so `font-family: "Instrument Sans"` in that document
 * resolves against nothing, and the card renders in whatever the SVG's default face is. The build
 * has the same problem and solves it by handing resvg explicit font files with
 * `loadSystemFonts: false`; the browser is handed the identical bytes, inlined into the SVG as an
 * `@font-face` whose `src` is a `data:` URI. Measured rather than assumed: with the font embedded
 * the raster is Instrument Sans, without it the same SVG is a fallback face with visibly different
 * ink, and the canvas is **not** tainted either way — a `data:` SVG that references nothing external
 * is same-origin, so `toBlob` and `getImageData` both work. That is what makes this path viable at
 * all: publishing needs nothing from a host but somewhere to put bytes.
 *
 * The cost is 259 KB of base64 per SVG, which never leaves the page — only the PNG is uploaded —
 * and one fetch of the 190 KB font per publish, cached by the browser like any other asset.
 *
 * ## Where the two rasterisers disagree, and why that is fine
 *
 * They are not byte-identical and they are not asked to be. They differ in two ways worth naming:
 *
 *  - **Text advances.** Node measures with HarfBuzz through `@kineglyph/export`; here we measure
 *    with the canvas, against the same font file. On this face they agree exactly at weight 400 and
 *    diverge by up to ~3.7% at 700 — because HarfBuzz is not applying the variable `wght` axis to
 *    its advances while both renderers *draw* at the requested weight. The browser is the more
 *    accurate of the two, and measuring the way we rasterise is the property that matters: text
 *    fits the boxes it was measured for. A title very near a wrap boundary can take a different
 *    number of lines on the two paths.
 *  - **Rasterisation.** Different anti-aliasing and gamma. Nobody can see it; a hash can.
 *
 * So the tests assert the things a reader would notice — the size, that it is a real PNG, that the
 * palette is the article's, that the ink lands where the composition puts it, that it is legible at
 * 300px — and never a digest of the bytes.
 */
// Bare specifier on purpose — see `kineglyph.ts`. `@pagina/core`'s card composer imports
// `@kineglyph/core`, which `vite.config.ts` aliases onto this same external runtime.
import { renderSvg, resolveFigure, seekTimeline } from "kineglyph";
import {
  CARD_FONT_FAMILY, OG_CARD_HEIGHT, OG_CARD_WIDTH, cardScene, glyphTheme, planCards, sha256Hex,
  type CardSpec, type Diagnostic, type DrawnCard, type PlannedCardSpec, type RenderedArticle,
} from "@pagina/core";
import type { ArticleStore } from "../store/article-store.js";
import { evaluateSceneModule } from "./kineglyph.js";

/** What `resolveFigure` takes, without reaching past `kineglyph`. */
type FigureSource = Parameters<typeof resolveFigure>[0];
type ThemeTokens = NonNullable<Parameters<typeof resolveFigure>[1]["theme"]>;
/** Kineglyph's text-measurer shape, borrowed rather than imported for the same reason. */
type TextFont = Parameters<NonNullable<Parameters<typeof resolveFigure>[1]["textMeasurer"]>["measureText"]>[1];

/**
 * How much bigger than its slot a glyph is rasterised, matching `og-render.ts`.
 *
 * The glyph is drawn to pixels and then composited into the card, so it is resampled once. At 1×
 * that resampling is visible on hairlines and small labels.
 */
const GLYPH_OVERSAMPLE = 2;

/** The font a card is set in, as both a measurable face and a string a `<style>` can carry. */
export interface CardFont {
  readonly family: string;
  /** `data:font/ttf;base64,…`, for the `@font-face` inlined into every card SVG. */
  readonly dataUri: string;
  /** SHA-256 of the font bytes, so a font swap invalidates every cached card — as in the build. */
  readonly digest: string;
  /** Measures against the loaded face, so layout and pixels come from the same outlines. */
  readonly measureText: (text: string, font: TextFont) => number;
}

/** Fetched once per URL per page: the bytes, the digest and the shaping are all reusable. */
const fonts = new Map<string, Promise<CardFont>>();

/**
 * The card font, loaded for measurement and for embedding.
 *
 * Registering the `FontFace` is what makes `measureText` mean anything: without it the canvas
 * measures a fallback and the card is laid out for a font it is not drawn in — which is the exact
 * defect this whole file exists to avoid, arrived at from the other direction.
 */
export async function loadCardFont(url: string): Promise<CardFont> {
  let pending = fonts.get(url);
  if (pending === undefined) {
    pending = (async (): Promise<CardFont> => {
      const response = await fetch(url);
      if (!response.ok) throw new Error(`${url} answered ${String(response.status)}`);
      const bytes = new Uint8Array(await response.arrayBuffer());
      const face = new FontFace(CARD_FONT_FAMILY, bytes.buffer as ArrayBuffer, { weight: "100 900" });
      await face.load();
      document.fonts.add(face);
      const canvas = document.createElement("canvas").getContext("2d");
      if (canvas === null) throw new Error("this browser has no 2d canvas context");
      return {
        family: CARD_FONT_FAMILY,
        dataUri: `data:font/ttf;base64,${base64(bytes)}`,
        digest: await sha256Hex(bytes),
        measureText: (text, font) => {
          if (text === "") return 0;
          canvas.font = `${String(font.weight)} ${String(font.size)}px "${CARD_FONT_FAMILY}", sans-serif`;
          const spacing = (font.letterSpacing ?? 0) * Math.max(0, [...text].length - 1);
          return canvas.measureText(text).width + spacing;
        },
      };
    })();
    fonts.set(url, pending);
  }
  try {
    return await pending;
  } catch (error) {
    // Not cached as a rejection: a font that 404'd because the host had not deployed it yet should
    // be retried on the next publish rather than remembered as broken for the life of the tab.
    fonts.delete(url);
    throw error;
  }
}

/** Bytes → base64, in chunks, because `String.fromCharCode(...200_000_bytes)` overflows the stack. */
function base64(bytes: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < bytes.length; i += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(i, i + 0x8000));
  }
  return btoa(binary);
}

/**
 * The same SVG, with the card's font embedded in it.
 *
 * Inserted after the opening tag rather than composed into the scene, because the font is a fact
 * about *rasterising* this document standalone and not about the picture — the build's SVG has no
 * `@font-face` in it at all and draws the same card.
 */
export function embedCardFont(svg: string, font: CardFont): string {
  const style = `<style>@font-face{font-family:"${font.family}";src:url("${font.dataUri}") format("truetype");font-weight:100 900;font-style:normal;}</style>`;
  const open = svg.indexOf(">");
  return open < 0 ? svg : `${svg.slice(0, open + 1)}${style}${svg.slice(open + 1)}`;
}

/**
 * SVG text → PNG bytes, at exactly `width` × `height`.
 *
 * The `<img>` is given an explicit box rather than left to the SVG's intrinsic size: an SVG whose
 * root carries a `viewBox` and percentage dimensions has no intrinsic size in some browsers, and
 * the difference between "1200×630" and "whatever the image decided" is the difference between a
 * card and a rejected one.
 */
export async function rasterisePng(svg: string, width: number, height: number): Promise<Blob> {
  const url = URL.createObjectURL(new Blob([svg], { type: "image/svg+xml;charset=utf-8" }));
  try {
    const image = new Image();
    image.width = width;
    image.height = height;
    await new Promise<void>((done, fail) => {
      image.onload = () => { done(); };
      image.onerror = () => { fail(new Error("the browser could not decode the card's SVG")); };
      image.src = url;
    });
    // `decode()` after `onload` because a font inside the document may still be being applied when
    // the load event fires; skipping it draws a card with no text on it, occasionally.
    if (typeof image.decode === "function") await image.decode();
    const canvas = document.createElement("canvas");
    canvas.width = width;
    canvas.height = height;
    const context = canvas.getContext("2d");
    if (context === null) throw new Error("this browser has no 2d canvas context");
    context.drawImage(image, 0, 0, width, height);
    const blob = await new Promise<Blob | null>((done) => { canvas.toBlob(done, "image/png"); });
    if (blob === null) throw new Error("the canvas produced no PNG");
    return blob;
  } finally {
    URL.revokeObjectURL(url);
  }
}

/** The glyph, rasterised and inlined — the same two-pass detour `og-render.ts` takes, and for the
 * same reason: a Kineglyph drawing paints through `var(--kg-color-*)`, and those references are not
 * resolved inside a nested `<image>`, so an SVG glyph spliced into the card rasters as a black
 * rectangle. */
async function renderGlyph(
  spec: CardSpec,
  source: string,
  box: { readonly width: number; readonly height: number },
  font: CardFont,
): Promise<string> {
  const module_ = await evaluateSceneModule(source);
  if (module_ === null || typeof module_ !== "object") {
    throw new Error(`${spec.glyph?.file ?? "the glyph"} must default-export a Kineglyph scene definition`);
  }
  const theme = glyphTheme(spec.palette, spec.palette.raised) as ThemeTokens;
  const scene = resolveFigure(module_ as FigureSource, {
    width: box.width,
    theme,
    textMeasurer: { measureText: font.measureText },
  });
  const errors = (scene.diagnostics ?? []).filter((d) => d.severity === "error");
  if (errors.length > 0) throw new Error(errors.map((d) => `${d.code}: ${d.message}`).join("; "));
  const duration = scene.timeline?.duration ?? 0;
  const time = spec.glyph?.time ?? "end";
  const at = time === "end" ? duration : time === "start" ? 0 : Math.min(time, duration);
  const frame = seekTimeline(scene, at);
  const svg = embedCardFont(renderSvg(frame, { idPrefix: "og-glyph" }), font);
  const png = await rasterisePng(svg, box.width * GLYPH_OVERSAMPLE, box.height * GLYPH_OVERSAMPLE);
  return `data:image/png;base64,${base64(new Uint8Array(await png.arrayBuffer()))}`;
}

/** Draws one card. Throws with a message naming the page when anything in it cannot be drawn. */
export async function drawCard(spec: CardSpec, font: CardFont, glyphSource?: string): Promise<Blob> {
  let glyph: { dataUri: string; alt: string } | undefined;
  if (spec.glyph !== undefined && glyphSource !== undefined) {
    const box = spec.template === "editorial"
      ? { width: spec.slotWidth, height: spec.height }
      : { width: spec.width, height: spec.template === "full" ? spec.height : Math.round(spec.height * 0.62) };
    glyph = { dataUri: await renderGlyph(spec, glyphSource, box, font), alt: spec.glyph.alt };
  }
  const { scene, theme } = cardScene({
    content: spec.content,
    palette: spec.palette,
    template: spec.template,
    width: spec.width,
    height: spec.height,
    slotWidth: spec.slotWidth,
    glyphPosition: spec.glyphPosition,
    ...(glyph === undefined ? {} : { glyph }),
  });
  const resolved = resolveFigure(scene as FigureSource, {
    width: spec.width,
    theme: theme as ThemeTokens,
    textMeasurer: { measureText: font.measureText },
  });
  const errors = (resolved.diagnostics ?? []).filter((d) => d.severity === "error");
  if (errors.length > 0) throw new Error(errors.map((d) => `${d.code}: ${d.message}`).join("; "));
  const frame = seekTimeline(resolved, resolved.timeline?.duration ?? 0);
  const svg = embedCardFont(renderSvg(frame, { idPrefix: "og-card" }), font);
  return rasterisePng(svg, spec.width, spec.height);
}

export interface RenderCardsOptions {
  /** Where the OFL font the cards are set in is served from. Without one, no cards are drawn. */
  readonly fontUrl?: string;
  /** `tokens.css` as the shell ships it, so the browser bakes the palette the build would bake. */
  readonly tokensCss?: string;
}

export interface RenderedCards {
  /** Page href → the card's URL and alt text, for `withOgCards`. */
  readonly cards: Map<string, DrawnCard>;
  readonly diagnostics: Diagnostic[];
}

const messageOf = (error: unknown): string => (error instanceof Error ? error.message : String(error));

/**
 * Every card this article wants, drawn and uploaded — skipping the ones that are already there.
 *
 * The skip is the same content-addressing the build uses, read from the other end: a card's file
 * name carries the hash of everything that can change the picture, so a page whose card is already
 * at that URL in the manifest needs nothing done. Without it a debounced save would redraw eleven
 * PNGs on every keystroke, which is both slow and a lot of pointless bytes through the backend.
 *
 * Nothing in here throws. A publish that cannot draw a picture is a publish, and a card is the last
 * thing that should be allowed to cost an author their work — so every failure becomes a warning,
 * that page keeps whatever `og:image` it had, and the rest of the cards still go up.
 */
export async function renderArticleCards(
  store: ArticleStore,
  article: RenderedArticle,
  options: RenderCardsOptions,
): Promise<RenderedCards> {
  const cards = new Map<string, DrawnCard>();
  const diagnostics: Diagnostic[] = [];
  const config = store.article;
  if (config === undefined) return { cards, diagnostics };

  if (options.fontUrl === undefined || options.fontUrl === "") {
    diagnostics.push({
      severity: "warning",
      code: "og-font-unavailable",
      message: "no card font is configured, so this publish drew no social cards; the pages keep the cards the last build wrote. Serve the font beside the editor bundle, or pass `cardFontUrl`.",
    });
    return { cards, diagnostics };
  }

  let font: CardFont;
  try {
    font = await loadCardFont(options.fontUrl);
  } catch (error) {
    // The honest failure. A card cannot be drawn in a font that would not load, and drawing it in
    // some other face would ship a picture that silently stopped looking like the site.
    diagnostics.push({
      severity: "warning",
      code: "og-font-unavailable",
      message: `the card font could not be loaded (${messageOf(error)}), so this publish drew no social cards; the pages keep the cards the last build wrote.`,
    });
    return { cards, diagnostics };
  }

  let planned: readonly PlannedCardSpec[];
  try {
    const plan = await planCards({
      article,
      config,
      ...(options.tokensCss === undefined ? {} : { tokensCss: options.tokensCss }),
      fontDigest: font.digest,
      fontFamily: font.family,
      readText: async (path) => {
        const mirrored = store.files.get(path)?.text;
        if (mirrored !== undefined) return mirrored;
        try {
          return (await store.open(path)).text ?? undefined;
        } catch {
          return undefined;
        }
      },
    });
    planned = plan.planned;
    diagnostics.push(...plan.diagnostics);
  } catch (error) {
    diagnostics.push({
      severity: "warning",
      code: "og-card-failed",
      message: `no social cards could be planned for this publish (${messageOf(error)}).`,
    });
    return { cards, diagnostics };
  }

  const base = store.base.replace(/\/$/, "");
  for (const card of planned) {
    // Already drawn — by this publish, an earlier one, or the last build. The name carries a hash
    // of everything that can change the picture, so a file already at that path *is* the picture
    // this plan describes, and the cheapest correct thing to do about it is nothing. This is the
    // same decision the build makes with `existsSync`, asked of the backend's file list instead.
    if (store.files.has(card.rel)) {
      cards.set(card.href, { url: `${base}/${card.rel}`, alt: card.alt });
      continue;
    }
    try {
      const blob = await drawCard(card.spec, font, card.glyphSource);
      const upload = await store.uploadFile(blob, card.rel);
      cards.set(card.href, { url: upload.url, alt: card.alt });
    } catch (error) {
      diagnostics.push({
        severity: "warning",
        code: "og-card-failed",
        message: `no social card could be drawn for this page (${messageOf(error)}), so it keeps the card it had.`,
        page: card.href,
      });
    }
  }
  return { cards, diagnostics };
}

export { OG_CARD_HEIGHT, OG_CARD_WIDTH };
